ae2f_docs: ae2f::errGlobState Struct Reference
ae2f::errGlobState Struct Reference
Gets the code.
#include <errGlob.hpp>
Public Member Functions
constexprmethod errGlobState (ae2f_err_t a) noexcept
constexprmethod const char * peek () const noexcept
Gets one.
constextendedmethod errGlobState pop () const noexcept
Pops an error with an error type.
std::string msgall () const noexcept
Generates the error message.
Static Public Member Functions
static errGlobState errGlobStateWithThrow (ae2f_err_t a)
It is a constructor, which will throw it is a state critical.
Public Attributes
ae2f_err_t code
Detailed Description
Gets the code.
Constructor & Destructor Documentation
errGlobState()
constexprmethod ae2f::errGlobState::errGlobState (ae2f_err_t a) noexcept
: code(a) {}
Member Function Documentation
errGlobStateWithThrow()
errGlobState ae2f::errGlobState::errGlobStateWithThrow (ae2f_err_t a) inline static
It is a constructor, which will throw it is a state critical.
Parameters
a Raw status code
Returns
error parser for a.
See also
ae2f_errGlobNormalised
{
  if (ae2f_errGlobNormalised(a))
    throw errGlobThrown(a);
  return a;
}
msgall()
std::string ae2f::errGlobState::msgall () const inline noexcept
Generates the error message.
Returns
A whole list of error messages.
{
  std::string rtn = "Following shows the error flag enabled.";
  errGlobState err(this->code);
  while (err.code) {
    rtn += '\t';
    rtn += err.peek();
    err = err.pop();
    rtn += '\n';
  }
  return rtn;
}
References peek(), and pop().
peek()
constexprmethod const char * ae2f::errGlobState::peek () const inline noexcept
Gets one.
Returns
A single error message for this code.
{
    return (code & ae2f_errGlob_IMP_NOT_FOUND)
               ? "Failed to find the function on preprocessor which is "
                 "callable "
                 "for some reason No operation has beed done."
           : (code & ae2f_errGlob_PTR_IS_NULL)
               ? "Failed to refer the pointer either l-value inside the "
                 "function."
           : (code & ae2f_errGlob_FLUSH_FAILED) ? "Failed freeing the memory."
           : (code & ae2f_errGlob_ALLOC_FAILED)
               ? "stdlib allocating functions (malloc, calloc, realloc) has "
                 "been "
                 "failed."
           : (code & ae2f_errGlob_WRONG_OPERATION)
               ? "Found that parameter sent by programmer is invalid. The "
                 "operation may have been ceased while the middle."
           : (code & ae2f_errGlob_NFOUND)
               ? "Found some errors, but not by parameters. The operation has "
                 "failed."
           : (code & ae2f_errGlob_DONE_HOWEV)
               ? "The operation went done. Note that operation may not be "
                 "valid."
           : (code) ? "Unexpected flag."
                    : "The operation went done.";
  }
Referenced by msgall().
pop()
constextendedmethod errGlobState ae2f::errGlobState::pop () const inline noexcept
Pops an error with an error type.
Returns
Error message
{
    return errGlobState(code & ~rBitVec<ae2f_err_t>(code).FndOne().obj);
  }
Referenced by msgall().
Member Data Documentation
code
ae2f_err_t ae2f::errGlobState::code
The documentation for this struct was generated from the following file:
submod/ae2f/Core/inc/ae2f/errGlob.hpp